#ifndef AD93XX_DEVICE_PARAMS_H
#define AD93XX_DEVICE_PARAMS_H

enum AD93xx_Device_Params
{
	AD93xx_CENTERFREQ = 0,
	AD93xx_SAMPLERATE,
	AD93xx_BANDWIDTH,
	AD93xx_PORTSELECT,
	AD93xx_GAINMODE,
	AD93xx_MANUALGAIN,
	AD93xx_ATTENUATION,
	AD93xx_FIRFILTER,
	AD93xx_FIRFILTERENABLE
};

#endif // AD93XX_DEVICE_PARAMS_H